name: BuildLinux

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  papercraft:
    name: ${{ inputs.name }}
    # Oldest LTS ubuntu still with support
    runs-on: ubuntu-20.04
    steps:
      - name: Install LinuxDeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: appimage
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          export PATH="$(pwd)/bin:$PATH"
          mkdir bin
          # Old G++ doesn't support -std=c++20, but it does support -std=c++2a
          # This script hacks that
          cp distro/docker/g++ bin/g++
          cp distro/docker/g++ bin/c++
          cargo build
          export VERSION="${{ inputs.name }}"
          export ARCH=x86_64
          # Create the directory tree
          linuxdeploy-x86_64.AppImage --appdir=AppDir
          mkdir -p AppDir/usr/share/metainfo/
          cp distro/papercraft.desktop AppDir/usr/share/applications/
          cp distro/com.rodrigorc.papercraft.appdata.xml AppDir/usr/share/metainfo/
          cp target/debug/papercraft AppDir/usr/bin/
          cp src/papercraft.png AppDir/usr/share/icons/hicolor/128x128/apps/
          linuxdeploy-x86_64.AppImage \
              --appdir=AppDir \
              --desktop-file=AppDir/usr/share/applications/papercraft.desktop \
              --output appimage \
              --exclude-library="libglib-2.0.*" \
              --custom-apprun=distro/docker/apprun
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Papercraft-${{ inputs.name }}-x86_64.AppImage
          path: Papercraft-${{ inputs.name }}-x86_64.AppImage
          if-no-files-found: error
