name: BuildMacOS

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string

jobs:
  papercraft:
    name: ${{ inputs.name }}
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          cargo build --release
          ls -l target/release
      - name: Upload artifact MacOS
        uses: actions/upload-artifact@v4
        with:
          name: Papercraft-${{ inputs.name }}-macos
          path: target/release/papercraft
          if-no-files-found: error

