name: BuildMacOS

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  papercraft:
    name: ${{ inputs.name }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Rustup
        run: |
          rustup target add x86_64-apple-darwin
      - name: Build x86
        run: |
          cargo build --release --target=x86_64-apple-darwin
      - name: Build Arm86
        run: |
          cargo build --release --target=aarch64-apple-darwin
      - name: Build Universal app
        run: |
          lipo -create target/aarch64-apple-darwin/release/papercraft target/x86_64-apple-darwin/release/papercraft -output Papercraft-${{ inputs.name }}-macOS-universal
      - name: Upload artifact MacOS
        uses: actions/upload-artifact@v4
        with:
          name: Papercraft-${{ inputs.name }}-macOS-universal
          path: Papercraft-${{ inputs.name }}-macOS-universal
          if-no-files-found: error

