name: test_linux

on:
  workflow_dispatch:
  push:
    branches:
      - 'Workflow'
    tags:
      - 'test'

jobs:
  release:
    permissions: write-all
    name: Release
    needs: build_linux
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: Papercraft-${{ github.ref_name }}-x86_64.AppImage
      - name: Upload to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: Papercraft-${{ github.ref_name }}-x86_64.AppImage
          draft: true
